services:
  web2:
    image: nginx:alpine
    labels:
      simpledeploy.endpoints.0.domain: abc.com
      simpledeploy.endpoints.0.tls: local
    networks:
      - default
      - simpledeploy-public
networks:
  simpledeploy-public:
    external: true
    name: simpledeploy-public
