export const serviceTemplates = [
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    icon: '🐘',
    description: 'Reliable open-source relational database',
    config: {
      image: 'postgres:16-alpine',
      environment: {
        POSTGRES_PASSWORD: 'changeme',
        POSTGRES_USER: 'postgres',
        POSTGRES_DB: 'app',
      },
      volumes: ['pgdata:/var/lib/postgresql/data'],
      restart: 'unless-stopped',
      healthcheck: {
        test: ['CMD-SHELL', 'pg_isready -U postgres'],
        interval: '10s',
        timeout: '5s',
        retries: 3,
        start_period: '30s',
      },
    },
  },
  {
    id: 'mysql',
    name: 'MySQL',
    icon: '🐬',
    description: 'Popular open-source relational database',
    config: {
      image: 'mysql:8',
      environment: {
        MYSQL_ROOT_PASSWORD: 'changeme',
        MYSQL_DATABASE: 'app',
        MYSQL_USER: 'app',
        MYSQL_PASSWORD: 'changeme',
      },
      volumes: ['mysqldata:/var/lib/mysql'],
      restart: 'unless-stopped',
      healthcheck: {
        test: ['CMD-SHELL', 'mysqladmin ping -h localhost'],
        interval: '10s',
        timeout: '5s',
        retries: 3,
        start_period: '30s',
      },
    },
  },
  {
    id: 'mariadb',
    name: 'MariaDB',
    icon: '🦭',
    description: 'Community-developed MySQL fork',
    config: {
      image: 'mariadb:11',
      environment: {
        MARIADB_ROOT_PASSWORD: 'changeme',
        MARIADB_DATABASE: 'app',
        MARIADB_USER: 'app',
        MARIADB_PASSWORD: 'changeme',
      },
      volumes: ['mariadbdata:/var/lib/mysql'],
      restart: 'unless-stopped',
      healthcheck: {
        test: ['CMD-SHELL', 'healthcheck.sh --connect --innodb_initialized'],
        interval: '10s',
        timeout: '5s',
        retries: 3,
        start_period: '30s',
      },
    },
  },
  {
    id: 'redis',
    name: 'Redis',
    icon: '🔴',
    description: 'In-memory data store and cache',
    config: {
      image: 'redis:7-alpine',
      volumes: ['redisdata:/data'],
      restart: 'unless-stopped',
      command: 'redis-server --appendonly yes',
      healthcheck: {
        test: ['CMD-SHELL', 'redis-cli ping'],
        interval: '10s',
        timeout: '5s',
        retries: 3,
        start_period: '30s',
      },
    },
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    icon: '🍃',
    description: 'Document-oriented NoSQL database',
    config: {
      image: 'mongo:7',
      environment: {
        MONGO_INITDB_ROOT_USERNAME: 'root',
        MONGO_INITDB_ROOT_PASSWORD: 'changeme',
      },
      volumes: ['mongodata:/data/db'],
      restart: 'unless-stopped',
      healthcheck: {
        test: ['CMD-SHELL', "mongosh --eval \"db.adminCommand('ping')\""],
        interval: '10s',
        timeout: '5s',
        retries: 3,
        start_period: '30s',
      },
    },
  },
  {
    id: 'rabbitmq',
    name: 'RabbitMQ',
    icon: '🐇',
    description: 'Message broker with management UI',
    config: {
      image: 'rabbitmq:3-management-alpine',
      environment: {
        RABBITMQ_DEFAULT_USER: 'guest',
        RABBITMQ_DEFAULT_PASS: 'changeme',
      },
      volumes: ['rabbitmqdata:/var/lib/rabbitmq'],
      ports: ['15672:15672'],
      restart: 'unless-stopped',
      healthcheck: {
        test: ['CMD-SHELL', 'rabbitmq-diagnostics -q ping'],
        interval: '10s',
        timeout: '5s',
        retries: 3,
        start_period: '30s',
      },
    },
  },
  {
    id: 'nginx',
    name: 'Nginx',
    icon: '🌐',
    description: 'Lightweight web server and reverse proxy',
    config: {
      image: 'nginx:alpine',
      ports: ['80:80'],
      restart: 'unless-stopped',
    },
  },
  {
    id: 'blank',
    name: 'Blank Service',
    icon: '📦',
    description: 'Start from scratch',
    config: {
      image: '',
      restart: 'unless-stopped',
    },
  },
];
