// Shared api mock used by component tests via `vi.mock('../../lib/api.js', ...)`.
// Each api method returns `{ data: ..., error: null }` by default.
import { vi } from 'vitest';

function ok(data) { return { data, error: null, status: 200 }; }

export function makeApiMock(overrides = {}) {
  const base = {
    login: vi.fn(async () => ok({})),
    logout: vi.fn(async () => ok({})),
    setupStatus: vi.fn(async () => ok({ configured: true })),
    setup: vi.fn(async () => ok({})),
    health: vi.fn(async () => ok(true)),
    listApps: vi.fn(async () => ok([])),
    getApp: vi.fn(async () => ok({})),
    removeApp: vi.fn(async () => ok({})),
    listArchived: vi.fn(async () => ok([])),
    purgeApp: vi.fn(async () => ok({})),
    deploy: vi.fn(async () => ok({})),
    getCompose: vi.fn(async () => ok('services: {}')),
    validateCompose: vi.fn(async () => ok({ ok: true })),
    restartApp: vi.fn(async () => ok({})),
    stopApp: vi.fn(async () => ok({})),
    startApp: vi.fn(async () => ok({})),
    pullApp: vi.fn(async () => ok({})),
    cancelDeploy: vi.fn(async () => ok({})),
    scaleApp: vi.fn(async () => ok({})),
    getAppServices: vi.fn(async () => ok([])),
    getEnv: vi.fn(async () => ok({})),
    putEnv: vi.fn(async () => ok({})),
    getComposeVersions: vi.fn(async () => ok([])),
    rollbackApp: vi.fn(async () => ok({})),
    deleteVersion: vi.fn(async () => ok({})),
    getDeployEvents: vi.fn(async () => ok([])),
    updateDomain: vi.fn(async () => ok({})),
    updateEndpoints: vi.fn(async () => ok({})),
    uploadCert: vi.fn(async () => ok({})),
    deleteCert: vi.fn(async () => ok({})),
    updateAccess: vi.fn(async () => ok({})),
    systemMetrics: vi.fn(async () => ok([])),
    appMetrics: vi.fn(async () => ok([])),
    appRequests: vi.fn(async () => ok([])),
    listBackupConfigs: vi.fn(async () => ok([])),
    createBackupConfig: vi.fn(async () => ok({})),
    updateBackupConfig: vi.fn(async () => ok({})),
    deleteBackupConfig: vi.fn(async () => ok({})),
    listBackupRuns: vi.fn(async () => ok([])),
    triggerBackup: vi.fn(async () => ok({})),
    triggerBackupConfig: vi.fn(async () => ok({})),
    restore: vi.fn(async () => ok({})),
    downloadBackupUrl: vi.fn((id) => `/api/backups/runs/${id}/download`),
    uploadRestore: vi.fn(async () => ok(true)),
    backupSummary: vi.fn(async () => ok({})),
    detectStrategies: vi.fn(async () => ok([])),
    testS3: vi.fn(async () => ok({})),
    updateComposeVersion: vi.fn(async () => ok({})),
    downloadComposeVersionUrl: vi.fn((slug, id) => `/api/apps/${slug}/versions/${id}/download`),
    restoreComposeVersion: vi.fn(async () => ok({})),
    listWebhooks: vi.fn(async () => ok([])),
    createWebhook: vi.fn(async () => ok({})),
    updateWebhook: vi.fn(async () => ok({})),
    deleteWebhook: vi.fn(async () => ok({})),
    testWebhook: vi.fn(async () => ok({})),
    listAlertRules: vi.fn(async () => ok([])),
    createAlertRule: vi.fn(async () => ok({})),
    updateAlertRule: vi.fn(async () => ok({})),
    deleteAlertRule: vi.fn(async () => ok({})),
    alertHistory: vi.fn(async () => ok([])),
    clearAlertHistory: vi.fn(async () => ok({})),
    listUsers: vi.fn(async () => ok([])),
    createUser: vi.fn(async () => ok({})),
    updateUser: vi.fn(async () => ok({})),
    deleteUser: vi.fn(async () => ok({})),
    listAPIKeys: vi.fn(async () => ok([])),
    createAPIKey: vi.fn(async () => ok({})),
    deleteAPIKey: vi.fn(async () => ok({})),
    getProfile: vi.fn(async () => ok({ username: 'admin', display_name: 'Admin' })),
    updateProfile: vi.fn(async () => ok({})),
    changePassword: vi.fn(async () => ok({})),
    listRegistries: vi.fn(async () => ok([])),
    createRegistry: vi.fn(async () => ok({})),
    updateRegistry: vi.fn(async () => ok({})),
    deleteRegistry: vi.fn(async () => ok({})),
    dockerInfo: vi.fn(async () => ok({ server_version: '24', compose_version: '2.21' })),
    gitStatus: vi.fn(async () => ok({ Enabled: false })),
    dockerDiskUsage: vi.fn(async () => ok({})),
    dockerImages: vi.fn(async () => ok([])),
    dockerRemoveImage: vi.fn(async () => ok({})),
    dockerNetworks: vi.fn(async () => ok([])),
    dockerVolumes: vi.fn(async () => ok([])),
    dockerRemoveNetwork: vi.fn(async () => ok({})),
    dockerRemoveVolume: vi.fn(async () => ok({})),
    dockerPruneContainers: vi.fn(async () => ok({})),
    dockerPruneImages: vi.fn(async () => ok({})),
    dockerPruneVolumes: vi.fn(async () => ok({})),
    dockerPruneBuildCache: vi.fn(async () => ok({})),
    dockerPruneAll: vi.fn(async () => ok({})),
    deployLogsWs: vi.fn(() => fakeWS()),
    systemLogsWs: vi.fn(() => fakeWS()),
    systemInfo: vi.fn(async () => ok({ simpledeploy: { version: '0.0.1-test' } })),
    systemStorageBreakdown: vi.fn(async () => ok({})),
    systemPruneMetrics: vi.fn(async () => ok({})),
    systemPruneRequestStats: vi.fn(async () => ok({})),
    systemVacuum: vi.fn(async () => ok({})),
    systemLogs: vi.fn(async () => ok([])),
    listActivity: vi.fn(async () => ok({ entries: [], next_before: 0 })),
    listAppActivity: vi.fn(async () => ok({ entries: [], next_before: 0 })),
    listRecentActivity: vi.fn(async () => ok([])),
    getActivity: vi.fn(async () => ok({})),
    getAuditConfig: vi.fn(async () => ok({ retention_days: 0 })),
    putAuditConfig: vi.fn(async () => ok({})),
    purgeActivity: vi.fn(async () => ok({})),
    systemBackupDownload: vi.fn(async () => ok(true)),
    systemBackupConfig: vi.fn(async () => ok({})),
    systemSetBackupConfig: vi.fn(async () => ok({})),
    systemBackupRuns: vi.fn(async () => ok([])),
    getPublicHost: vi.fn(async () => ok({ public_host: '' })),
    exportApp: vi.fn(async () => ok(new Blob(['zip'], { type: 'application/zip' }))),
    importApp: vi.fn(async () => ok({ slug: 'imported', mode: 'new' })),
    importAppPreview: vi.fn(async () => ok({
      mode: 'overwrite',
      slug: 'existing',
      current: { compose: 'old', sidecar: '' },
      incoming: { compose: 'new', sidecar: '', manifest: {} },
      changes: {
        compose_changed: true,
        sidecar_changed: false,
        alert_rule_count_current: 1,
        alert_rule_count_incoming: 3,
        alert_rule_count_delta: 2,
        backup_config_count_current: 0,
        backup_config_count_incoming: 1,
        backup_config_count_delta: 1,
      },
    })),
    setPublicHost: vi.fn(async () => ok({})),
  };
  return { ...base, ...overrides };
}

function fakeWS() {
  return {
    onmessage: null,
    onclose: null,
    onerror: null,
    onopen: null,
    send: () => {},
    close: () => {},
  };
}
